export const ACTIVITY_ACTION = {
    AUTH_LOGIN: 'auth.login',
    AUTH_LOGIN_FAILED: 'auth.login.failed',
    AUTH_PASSWORD_RECOVERY: 'auth.password.recovery',
    AUTH_PASSWORD_RESET: 'auth.password.reset',
    USER_CREATE: 'user.create',
    USER_UPDATE: 'user.update',
    USER_DEACTIVATE: 'user.deactivate',
    USER_RESET_PASSWORD: 'user.reset_password',
    USER_CHANGE_CATEGORY: 'user.change_category',
    USER_CHANGE_GRADO: 'user.change_grado',
    USER_CHANGE_OFICIALIDAD: 'user.change_oficialidad',
    USER_ASSIGN_TARIFA: 'user.assign_tarifa',
    FEED_CREATE: 'feed.create',
    FEED_UPDATE: 'feed.update',
    FEED_DELETE: 'feed.delete',
    EVENTO_CREATE: 'evento.create',
    EVENTO_UPDATE: 'evento.update',
    EVENTO_DELETE: 'evento.delete',
    EVENTO_IMPORT: 'evento.import',
    DOCUMENTO_CREATE: 'documento.create',
    DOCUMENTO_UPDATE: 'documento.update',
    DOCUMENTO_DELETE: 'documento.delete',
    LIBRO_CREATE: 'libro.create',
    LIBRO_UPDATE: 'libro.update',
    LIBRO_DELETE: 'libro.delete',
    TRAZADO_CREATE: 'trazado.create',
    TRAZADO_UPDATE: 'trazado.update',
    TRAZADO_DELETE: 'trazado.delete',
    TESORERIA_ENTRADA_CREATE: 'tesoreria.entrada.create',
    TESORERIA_ENTRADA_UPDATE: 'tesoreria.entrada.update',
    TESORERIA_ENTRADA_DELETE: 'tesoreria.entrada.delete',
    TESORERIA_ENTRADA_BULK: 'tesoreria.entrada.bulk',
    TESORERIA_SALIDA_CREATE: 'tesoreria.salida.create',
    TESORERIA_SALIDA_UPDATE: 'tesoreria.salida.update',
    TESORERIA_SALIDA_DELETE: 'tesoreria.salida.delete',
    TESORERIA_TARIFA_CREATE: 'tesoreria.tarifa.create',
    TESORERIA_TARIFA_UPDATE: 'tesoreria.tarifa.update',
    TESORERIA_TARIFA_DELETE: 'tesoreria.tarifa.delete',
} as const;

export type ActivityAction = (typeof ACTIVITY_ACTION)[keyof typeof ACTIVITY_ACTION];

export const ACTIVITY_ENTITY = {
    USER: 'User',
    FEED: 'Feed',
    EVENTO: 'Evento',
    DOCUMENTO: 'Documento',
    TRAZADO: 'Trazado',
    BIBLIOTECA: 'Biblioteca',
    ENTRADA: 'EntradaDinero',
    SALIDA: 'SalidaDinero',
    TARIFA: 'TarifaCuota',
    AUTH: 'Auth',
} as const;

export type ActivityEntity = (typeof ACTIVITY_ENTITY)[keyof typeof ACTIVITY_ENTITY];

export const ACTIVITY_STATUS = {
    SUCCESS: 'success',
    FAILURE: 'failure',
    WARNING: 'warning',
} as const;

export type ActivityStatus = (typeof ACTIVITY_STATUS)[keyof typeof ACTIVITY_STATUS];

// Etiquetas legibles para los filtros de la vista
export const ACTIVITY_ACTION_LABEL: Record<ActivityAction, string> = {
    'auth.login': 'Inicio de sesión',
    'auth.login.failed': 'Login fallido',
    'auth.password.recovery': 'Recuperación de clave',
    'auth.password.reset': 'Cambio de clave',
    'user.create': 'Crear usuario',
    'user.update': 'Editar usuario',
    'user.deactivate': 'Desactivar usuario',
    'user.reset_password': 'Resetear clave',
    'user.change_category': 'Cambiar categoría',
    'user.change_grado': 'Cambiar grado',
    'user.change_oficialidad': 'Cambiar oficialidad',
    'user.assign_tarifa': 'Asignar tarifa',
    'feed.create': 'Crear publicación',
    'feed.update': 'Editar publicación',
    'feed.delete': 'Eliminar publicación',
    'evento.create': 'Crear evento',
    'evento.update': 'Editar evento',
    'evento.delete': 'Eliminar evento',
    'evento.import': 'Importar eventos',
    'documento.create': 'Crear documento',
    'documento.update': 'Editar documento',
    'documento.delete': 'Eliminar documento',
    'libro.create': 'Crear libro',
    'libro.update': 'Editar libro',
    'libro.delete': 'Eliminar libro',
    'trazado.create': 'Crear trazado',
    'trazado.update': 'Editar trazado',
    'trazado.delete': 'Eliminar trazado',
    'tesoreria.entrada.create': 'Registrar ingreso',
    'tesoreria.entrada.update': 'Editar ingreso',
    'tesoreria.entrada.delete': 'Eliminar ingreso',
    'tesoreria.entrada.bulk': 'Ingresar cuotas múltiples',
    'tesoreria.salida.create': 'Registrar egreso',
    'tesoreria.salida.update': 'Editar egreso',
    'tesoreria.salida.delete': 'Eliminar egreso',
    'tesoreria.tarifa.create': 'Crear tarifa',
    'tesoreria.tarifa.update': 'Editar tarifa',
    'tesoreria.tarifa.delete': 'Eliminar tarifa',
};
